repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-docstring-first
    - id: check-json
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: check-yaml
    - id: debug-statements
    - id: double-quote-string-fixer
    - id: trailing-whitespace
  - repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
    - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
